Task3 : myMain.o myStrFunc.o myMathFunc.o    
	gcc myMain.o myStrFunc.o myMathFunc.o -o Task3

myMathFunc.o : myMathFunc.c
	gcc -c myMathFunc.c
myStrFunc.o : myStrFunc.c
	gcc -c myStrFunc.c
myMain.o : myMain.c
	gcc -c myMain.c
